### ISSUE TITLE
Codespace is not launching using the repo?

### ISSUE THREAD

**Issue by lokeshkri** [microsoft/assistant-pf-demo#4]
Hello,
I tried launching the pf-demo in git vs codespaces, I am getting the following error message, can you let me know how to solve the issue? I also attempted to install it locally on Win OS, there are multiple issues there as well. I would like to try this repo out as I found it to be quite interesting in MS build conf.

**From git codespaces**
A codespace cannot be created because no machine types are available. You may need to select a different branch, modify your container configuration, or adjust your organization's policy settings.

**From windows**
CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda/win-64/repodata.json.zst (Caused by SSLError(SSLEOFError(
OFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

**Comment by luigiw** [comment]
I removed hostRequirements from `devcontainer.json`. Can you give code space another try?

**Comment by luigiw** [comment]
What command caused the error on Windows, can you paste the full stacktrace?

**Comment by lokeshkri** [comment]
PS C:\>
conda env create -f environment.yml
Retrieving notices: ...working... done
Channels:
 - anaconda
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): / Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLE
OFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/main/noarch/repodata.json.zst

\ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/r/noarch/repodata.json.zst

| Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pytorch/noarch/repodata.json.zst

/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /conda-forge/win-64/repodata.json.zst

/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/msys2/noarch/repodata.json.zst

\ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /conda-forge/noarch/repodata.json.zst

| Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/msys2/win-64/repodata.json.zst

/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING]
 EOF occurred in violation of protocol (_ssl.c:1000)'))': /anaconda/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING]
 EOF occurred in violation of protocol (_ssl.c:1000)'))': /anaconda/win-64/repodata.json.zst

- Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pytorch/win-64/repodata.json.zst

\ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/main/win-64/repodata.json.zst

- Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/main/noarch/repodata.json.zst

\ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/r/noarch/repodata.json.zst

- Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pytorch/noarch/repodata.json.zst

/ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /pkgs/msys2/noarch/repodata.json.zst

\ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /conda-forge/noarch/repodata.json.zst

- Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READIN
G] EOF occurred in violation of protocol (_ssl.c:1000)'))': /conda-forge/win-64/repodata.json.zst

**Comment by lokeshkri** [comment]
When I tried executing the process using codespaces, noticed the following error:

Traceback (most recent call last):
  File "/workspaces/assistant-pf-demo/src/assistant_flow/setup.py", line 101, in <module>
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/assistant/lib/python3.11/site-packages/openai/resources/beta/assistants.py", line 156, in create
    return self._post(
           ^^^^^^^^^^^
  File "/opt/conda/envs/assistant/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/assistant/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/opt/conda/envs/assistant/lib/python3.11/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'type': 'invalid_request_error', 'param': 'model', 'code': 'model_not_found'}}

**Comment by lokeshkri** [comment]
Do you have any further updates on the error messages?
