### ISSUE TITLE
assistant flow setup fails with character limit here

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/assistant-pf-demo#6]
Tried the vanilla sample, and updated my openai uri and key details in .env. However setup.py call failed. Any idea what to change in sample? Perhaps, "sales_data_insights" function description content need to be reduced. Is it?

$ python src/assistant_flow/setup.py
..
..
OPENAI_API_VERSION 2024-05-01-preview
Traceback (most recent call last):
  File "/mnt/d/work/practice/AI/llm/assistant-pf-demo/src/assistant_flow/setup.py", line 101, in <module>
    assistant = client.beta.assistants.create(
  File "/home/udev/miniconda3/envs/llmenv/lib/python3.9/site-packages/openai/resources/beta/assistants.py", line 156, in create
    return self._post(
  File "/home/udev/miniconda3/envs/llmenv/lib/python3.9/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/udev/miniconda3/envs/llmenv/lib/python3.9/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/udev/miniconda3/envs/llmenv/lib/python3.9/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools[1].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 1919 instead.", 'type': 'invalid_request_error', 'param': 'tools[1].function.description', 'code': 'string_above_max_length'}}

**Comment by diego2glez** [comment]
I had the same issue with that api version.
I reduced the function description (using gpt also 😆 ).
Seems to work fine:

"get some data insights about the contoso sales data in the following structure:
	Number_of_Orders INTEGER
	Sum_of_Order_Value_USD REAL
	Sum_of_Number_of_Items REAL
	Number_of_Orders_with_Discount INTEGER
	Sum_of_Discount_Percentage REAL
	Sum_of_Shipping_Cost_USD REAL
	Number_of_Orders_Returned INTEGER
	Number_of_Orders_Cancelled INTEGER
	Sum_of_Time_to_Fulfillment REAL
	Number_of_Orders_Repeat_Customers INTEGER
	Year INTEGER
	Month INTEGER
	Day INTEGER
	Date TIMESTAMP
	Day_of_Week INTEGER in 0 based format, Monday is 0
	main_category TEXT
	sub_category TEXT
	product_type TEXT
	Region TEXT
  If you are unsure of the data available, you can ask for a list of categories, days, etc.
  - query for all the values for the main_category
  The data will be returned in a json format in the data property of the returned object with the query used to get the data in the query property.
  If a query cannot be answered, the tool will return a message in the error property of the returned object."
